import './icon.css'

export * from './arrow-back'
export * from './arrow-forward'
export * from './close'
export * from './eye'
export * from './eye-blocked'
export * from './search'
export * from './spinner'

export * from './calendario'
export * from './imagem'
export * from './localizacao'
export * from './menu'
export * from './pesquisar'
export * from './pessoa'
